# Generated by Django 3.2 on 2022-03-30 09:46

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('totiemb', '0002_auto_20220330_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='products',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.CharField(default='£0.00', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='product_size',
            field=models.CharField(default='0 ml', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
