# Generated by Django 3.2 on 2022-03-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totiemb', '0003_auto_20220330_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
