# Generated by Django 3.2 on 2022-03-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totiemb', '0004_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
    ]
