# Generated by Django 3.2 on 2022-03-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totiemb', '0008_auto_20220330_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
