# Generated by Django 3.2 on 2022-03-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totiemb', '0009_alter_customer_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date_time', models.DateTimeField(auto_now_add=True)),
                ('over_18_yrs', models.BooleanField(default=False)),
                ('TandC_understood', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='totiemb.customer')),
            ],
            options={
                'ordering': ['-session_date_time'],
            },
        ),
    ]
