# Generated by Django 3.2 on 2022-03-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totiemb', '0010_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
