# Generated by Django 3.2 on 2022-03-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totiemb', '0012_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
